CREATE TABLE OBJTYPE
(
    OBJECT_TYPE_ID NUMBER(20)   NOT NULL ENABLE,
    PARENT_ID      NUMBER(20),
    CODE           VARCHAR2(40) NOT NULL UNIQUE,
    NAME           VARCHAR2(200 BYTE),
    DESCRIPTION    VARCHAR2(1000 BYTE),
    CONSTRAINT CON_OBJECT_TYPE_ID PRIMARY KEY (OBJECT_TYPE_ID),
    CONSTRAINT CON_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID) ON DELETE CASCADE ENABLE
);

CREATE TABLE ATTRTYPE
(
    ATTR_ID            NUMBER(20) NOT NULL,
    OBJECT_TYPE_ID     NUMBER(20) NOT NULL,
    OBJECT_TYPE_ID_REF NUMBER(20),
    CODE               VARCHAR2(40),
    NAME               VARCHAR2(200 BYTE),
    CONSTRAINT CON_ATTR_ID PRIMARY KEY (ATTR_ID),
    CONSTRAINT CON_ATTR_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID),
    CONSTRAINT CON_ATTR_OBJECT_TYPE_ID_REF FOREIGN KEY (OBJECT_TYPE_ID_REF) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

CREATE TABLE OBJECTS
(
    OBJECT_ID      NUMBER(20) NOT NULL,
    PARENT_ID      NUMBER(20),
    OBJECT_TYPE_ID NUMBER(20) NOT NULL,
    NAME           VARCHAR2(2000 BYTE),
    DESCRIPTION    VARCHAR2(4000 BYTE),
    CONSTRAINT CON_OBJECTS_ID PRIMARY KEY (OBJECT_ID),
    CONSTRAINT CON_PARENTS_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE DEFERRABLE,
    CONSTRAINT CON_OBJ_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

CREATE TABLE ATTRIBUTES
(
    ATTR_ID    number(10) not null,
    OBJECT_ID  number(20) not null,
    VALUE      varchar2(4000 byte),
    DATE_VALUE date,
    constraint con_ATR_attr_id foreign key (ATTR_ID) references AttrType (attr_id) on delete cascade,
    constraint con_ATR_object_id foreign key (OBJECT_ID) references Objects (object_id) on delete cascade
);

CREATE TABLE OBJREFERENCE
(
    ATTR_ID   NUMBER(20) NOT NULL,
    REFERENCE NUMBER(20) NOT NULL,
    OBJECT_ID NUMBER(20) NOT NULL,
    CONSTRAINT CON_OBJREFERENCE_PK PRIMARY KEY (ATTR_ID, REFERENCE, OBJECT_ID),
    CONSTRAINT CON_REFERENCE FOREIGN KEY (REFERENCE) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ROBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_RATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
);

create sequence SEQ_FOR_OBJECT
    start with 1
    increment by 1;

create sequence SEQ_FOR_OBJTYPE
    start with 19
    increment by 1;

create sequence SEQ_FOR_ATTRTYPE
    start with 169
    increment by 1;