package eav.names;

public class AttributeName {

    //attr_type_id
    //users
    public static final Long ATTR_TYPE_ID_USERS_ID = 1L;
    public static final Long ATTR_TYPE_ID_USERS_LOGIN = 2L;
    public static final Long ATTR_TYPE_ID_USERS_PASSWORD = 3L;
    public static final Long ATTR_TYPE_ID_USERS_LAST_LOGIN_DATE = 4L;
    public static final Long ATTR_TYPE_ID_USERS_ARCHVIVE = 5L;
    public static final Long ATTR_TYPE_ID_USERS_ROLE_ID = 6L;

    //USER_STATUS
    public static final Long ATTR_TYPE_ID_USER_STATUS_ID = 7L;
    public static final Long ATTR_TYPE_ID_USER_STATUS_DESCRIPTION = 8L;

    //STUDENT_DETAIL
    public static final Long ATTR_TYPE_ID_STUDENT_DETAIL_ID = 9L;
    public static final Long ATTR_TYPE_ID_STUDENT_DETAIL_POSITION_ID = 10L;
    public static final Long ATTR_TYPE_ID_STUDENT_DETAIL_USER_STATUS_ID = 11L;
    public static final Long ATTR_TYPE_ID_STUDENT_DETAIL_USER_ID = 12L;

    //ROLE
    public static final Long ATTR_TYPE_ID_ROLE_ID = 13L;
    public static final Long ATTR_TYPE_ID_ROLE_DESCRIPTION = 14L;

    //RESUME_STATUS
    public static final Long ATTR_TYPE_ID_RESUME_STATUS_ID = 15L;
    public static final Long ATTR_TYPE_ID_RESUME_STATUS_DESCRIPTION = 16L;

    //RESUME_KNOWLEDGE
    public static final Long ATTR_TYPE_ID_RESUME_KNOWLEDGE_ID = 17L;
    public static final Long ATTR_TYPE_ID_RESUME_KNOWLEDGE_KNOWLEDGE_LEVEL = 18L;
    public static final Long ATTR_TYPE_ID_RESUME_KNOWLEDGE_KNOWLEDGE_TYPE = 19L;
    public static final Long ATTR_TYPE_ID_RESUME_KNOWLEDGE_RESUME_ID = 20L;

    //RESUME
    public static final Long ATTR_TYPE_ID_RESUME_ID = 21L;
    public static final Long ATTR_TYPE_ID_RESUME_VERSION = 22L;
    public static final Long ATTR_TYPE_ID_RESUME_ERROR_DESCRIPTION = 23L;
    public static final Long ATTR_TYPE_ID_RESUME_MODIFIED_DATE = 24L;
    public static final Long ATTR_TYPE_ID_RESUME_APPROVED_DATE = 25L;
    public static final Long ATTR_TYPE_ID_RESUME_NAME = 26L;
    public static final Long ATTR_TYPE_ID_RESUME_SURNAME = 27L;
    public static final Long ATTR_TYPE_ID_RESUME_ENG_NAME = 28L;
    public static final Long ATTR_TYPE_ID_RESUME_ENG_SURNAME = 29L;
    public static final Long ATTR_TYPE_ID_RESUME_LAST_NAME = 30L;
    public static final Long ATTR_TYPE_ID_RESUME_EMAIL = 31L;
    public static final Long ATTR_TYPE_ID_RESUME_TELEPHONE_NUM = 32L;
    public static final Long ATTR_TYPE_ID_RESUME_SKYPE = 33L;
    public static final Long ATTR_TYPE_ID_RESUME_PHOTO_PATH = 34L;
    public static final Long ATTR_TYPE_ID_RESUME_RESUME_STATUS_ID = 35L;
    public static final Long ATTR_TYPE_ID_RESUME_USER_ID = 36L;

    //QA_RESUME_DETAIL
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_ID = 37L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_INSTITUTE_OTHER_NAME = 38L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_COURSE = 39L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_FACULTY = 40L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_GRADUATION_YEAR = 41L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_IS_STUDENT = 42L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_CONTACTS = 43L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_TRAINING_CENTER_INTEREST = 44L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = 45L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_INTEREST = 46L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_DEVELOPMENT = 47L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT = 48L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_JOB_INTERESTS = 49L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_EXPERT_WORK_TYPE = 50L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_AUTOMATION_WORK_TYPE = 51L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_DEVELOPMENT_WORK_TYPE = 52L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT_WORK_TYPE = 53L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_LEADERSHIP_WORK_TYPE = 54L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = 55L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_SOFTWARE_DEV_LIFE_CYCLE = 56L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_QA_ROLE_IN_LIFE_CYCLE = 57L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_WHAT_IS_TEST_CASE = 58L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_WHAT_IS_DEFECT = 59L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_TESTING_TYPE = 60L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_NETWORK_TECHNOLOGY = 61L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_OOP = 62L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_DB_SQL = 63L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_CLIENT_SERVER_ARCHITECTURE = 64L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_OTHER_SKILL_LEVEL = 65L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_WORK_EXPERIENCE = 66L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_ENGLISH_READ_LEVEL = 67L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = 68L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = 69L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = 70L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = 71L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_MORE_INFORMATION_ADOUT_YOU = 72L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_INSTITUTE_ID = 73L;
    public static final Long ATTR_TYPE_ID_QA_RESUME_DETAIL_RESUME_ID = 74L;

    //QA_INTERVIEW_RESULT_DETAIL
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_ID = 75L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_COME_TO_INTERVIEW = 76L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = 77L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = 78L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = 79L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_1 = 80L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_2 = 81L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_3 = 82L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_4 = 83L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_5 = 84L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_6 = 85L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_1 = 86L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_2 = 87L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_3 = 88L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_4 = 89L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_FINAL_ASSESSMENT = 90L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_BASIC_INFORMATION = 91L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = 92L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = 93L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_COME_TO_INTERVIEW = 94L;
    public static final Long ATTR_TYPE_ID_QA_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = 95L;

    //POSITION
    public static final Long ATTR_TYPE_ID_POSITION_ID = 96L;
    public static final Long ATTR_TYPE_ID_POSITION_DESCRIPTION = 97L;

    //MAIL_QUEUE
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_ID = 98L;
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_ADDED_WHEN = 99L;
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_IS_SENT = 100L;
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_IS_INCORRECT_MAIL = 101L;
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_RECIVER_ADDRESS = 102L;
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_MESSAGE_SUBJECT = 103L;
    public static final Long ATTR_TYPE_ID_MAIL_QUEUE_MESSAGE_BODY = 104L;

    //KNOWLEDGE_TYPE
    public static final Long ATTR_TYPE_ID_KNOWLEDGE_TYPE_ID = 105L;
    public static final Long ATTR_TYPE_ID_KNOWLEDGE_TYPE_DESCRIPTION = 106L;

    //INTERVIEW_SLOT
    public static final Long ATTR_TYPE_ID_INTERVIEW_SLOT_ID = 107L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_SLOT_TIME = 108L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_SLOT_INTERVIEW_ID = 109L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_SLOT_USER_ID = 110L;

    //INTERVIEW_RESULT
    public static final Long ATTR_TYPE_ID_INTERVIEW_RESULT_INTERVIEW_SLOT_ID = 111L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_RESULT_IS_COME = 112L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_RESULT_HR_USER_ID = 113L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_RESULT_INTERVIEWER_USER_ID = 114L;

    //INTERVIEW
    public static final Long ATTR_TYPE_ID_INTERVIEW_ID = 115L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_LOGIN = 116L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_START_TIME = 117L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_END_TIME = 118L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_HR_TIME_FOR_INTERVIEW = 119L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_INTERVIEW_TIME_FOR_INTERVIEW = 120L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_TOTAL_PLACE_COUNT = 121L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_AVAILABLE_PLACE_COUNT = 122L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_INTERVIEW_COUNT = 123L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_HR_COUNT = 124L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_ENABLE = 125L;
    public static final Long ATTR_TYPE_ID_INTERVIEW_POSITION_ID = 126L;

    //INSTITUTE
    public static final Long ATTR_TYPE_ID_INSTITUTE_ID = 127L;
    public static final Long ATTR_TYPE_ID_INSTITUTE_DESCRIPTION = 128L;

    //DEV_RESUME_DETAIL
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_ID = 129L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_INSTITUTE_OTHER_NAME = 130L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_COURCE = 131L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_FACULTY = 132L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_DEPARTMENT = 133L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_SPECIALITY = 134L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_GRADUATION_YEAR = 135L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_CONTACTS = 136L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_TRAINING_CENTER_INTEREST = 137L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = 138L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_JOB_INTEREST = 139L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_BACK_END_INTEREST = 140L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_FRONT_END_INTEREST = 141L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_DB_INTEREST = 142L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = 143L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_OPP_LEVEL = 144L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_DB_LEVEL = 145L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_WEB_LEVEL = 146L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_USER_INTERFACE_LEVEL = 147L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_UML_LEVEL = 148L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_OTHER_SKILL_LEVEL = 149L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_WORK_EXPERIENCEL = 150L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_ENGLISH_READ_LEVEL = 151L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = 152L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = 153L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = 154L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = 155L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_MORE_INFORMATION_ABOUT_YOU = 156L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_INSTITUTE_ID = 157L;
    public static final Long ATTR_TYPE_ID_DEV_RESUME_DETAIL_RESUME_ID = 158L;

    //DEV_INTERVIEW_RESULT_DETAIL
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_ID = 159L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_JAVA_SKILL = 160L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_SQL_SKILL = 161L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = 162L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = 163L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = 164L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = 165L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_DEV_FINAL_ASSESSMENT = 166L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = 167L;
    public static final Long ATTR_TYPE_ID_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = 168L;


    //attr_type_code
    //users
    public static final String ATTR_TYPE_CODE_USERS_ID = "ID";
    public static final String ATTR_TYPE_CODE_USERS_LOGIN = "LOGIN";
    public static final String ATTR_TYPE_CODE_USERS_PASSWORD = "PASSWORD";
    public static final String ATTR_TYPE_CODE_USERS_LAST_LOGIN_DATE = "LAST_LOGIN_DATE";
    public static final String ATTR_TYPE_CODE_USERS_ARCHVIVE = "ARCHVIVE";
    public static final String ATTR_TYPE_CODE_USERS_ROLE_ID = "ROLE_ID";

    //USER_STATUS
    public static final String ATTR_TYPE_CODE_USER_STATUS_ID = "ID";
    public static final String ATTR_TYPE_CODE_USER_STATUS_DESCRIPTION = "DESCRIPTION";

    //STUDENT_DETAIL
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_POSITION_ID = "POSITION_ID";
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_USER_STATUS_ID = "USER_STATUS_ID";
    public static final String ATTR_TYPE_CODE_STUDENT_DETAIL_USER_ID = "USER_ID";

    //ROLE
    public static final String ATTR_TYPE_CODE_ROLE_ID = "ID";
    public static final String ATTR_TYPE_CODE_ROLE_DESCRIPTION = "DESCRIPTION";

    //RESUME_STATUS
    public static final String ATTR_TYPE_CODE_RESUME_STATUS_ID = "ID";
    public static final String ATTR_TYPE_CODE_RESUME_STATUS_DESCRIPTION = "DESCRIPTION";

    //RESUME_KNOWLEDGE
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_ID = "ID";
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_KNOWLEDGE_LEVEL = "KNOWLEDGE_LEVEL";
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_KNOWLEDGE_TYPE = "KNOWLEDGE_TYPE";
    public static final String ATTR_TYPE_CODE_RESUME_KNOWLEDGE_RESUME_ID = "RESUME_ID";

    //RESUME
    public static final String ATTR_TYPE_CODE_RESUME_ID = "ID";
    public static final String ATTR_TYPE_CODE_RESUME_VERSION = "VERSION";
    public static final String ATTR_TYPE_CODE_RESUME_ERROR_DESCRIPTION = "ERROR_DESCRIPTION";
    public static final String ATTR_TYPE_CODE_RESUME_MODIFIED_DATE = "MODIFIED_DATE";
    public static final String ATTR_TYPE_CODE_RESUME_APPROVED_DATE = "APPROVED_DATE";
    public static final String ATTR_TYPE_CODE_RESUME_NAME = "NAME";
    public static final String ATTR_TYPE_CODE_RESUME_SURNAME = "SURNAME";
    public static final String ATTR_TYPE_CODE_RESUME_ENG_NAME = "ENG_NAME";
    public static final String ATTR_TYPE_CODE_RESUME_ENG_SURNAME = "ENG_SURNAME";
    public static final String ATTR_TYPE_CODE_RESUME_LAST_NAME = "LAST_NAME";
    public static final String ATTR_TYPE_CODE_RESUME_EMAIL = "EMAIL";
    public static final String ATTR_TYPE_CODE_RESUME_TELEPHONE_NUM = "TELEPHONE_NUM";
    public static final String ATTR_TYPE_CODE_RESUME_SKYPE = "SKYPE";
    public static final String ATTR_TYPE_CODE_RESUME_PHOTO_PATH = "PHOTO_PATH";
    public static final String ATTR_TYPE_CODE_RESUME_RESUME_STATUS_ID = "RESUME_STATUS_ID";
    public static final String ATTR_TYPE_CODE_RESUME_USER_ID = "USER_ID";

    //QA_RESUME_DETAIL
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_INSTITUTE_OTHER_NAME = "INSTITUTE_OTHER_NAME";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_COURSE = "COURSE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_FACULTY = "FACULTY";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_GRADUATION_YEAR = "GRADUATION_YEAR";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_IS_STUDENT = "IS_STUDENT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_IS_OTHER_CONTACTS = "OTHER_CONTACTS";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_TRAINING_CENTER_INTEREST = "TRAINING_CENTER_INTEREST";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = "WORK_IN_NETCRACKER_INTEREST";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_INTEREST = "OTHER_INTEREST";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_DEVELOPMENT = "QA_DEVELOPMENT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_JOB_INTERESTS = "OTHER_JOB_INTERESTS";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_EXPERT_WORK_TYPE = "QA_EXPERT_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_AUTOMATION_WORK_TYPE = "QA_AUTOMATION_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_DEVELOPMENT_WORK_TYPE = "QA_DEVELOPMENT_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_SOFTWARE_DEVELOPMENT_WORK_TYPE = "SOFTWARE_DEVELOPMENT_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_LEADERSHIP_WORK_TYPE = "LEADERSHIP_WORK_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = "OTHER_WORK_TYPE_SPECIFIC";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_SOFTWARE_DEV_LIFE_CYCLE = "SOFTWARE_DEV_LIFE_CYCLE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_QA_ROLE_IN_LIFE_CYCLE = "QA_ROLE_IN_LIFE_CYCLE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHAT_IS_TEST_CASE = "WHAT_IS_TEST_CASE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHAT_IS_DEFECT = "WHAT_IS_DEFECT";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_TESTING_TYPE = "TESTING_TYPE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_NETWORK_TECHNOLOGY = "NETWORK_TECHNOLOGY";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OOP = "OOP";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_DB_SQL = "DB_SQL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_CLIENT_SERVER_ARCHITECTURE = "CLIENT_SERVER_ARCHITECTURE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_OTHER_SKILL_LEVEL = "OTHER_SKILL_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WORK_EXPERIENCE = "WORK_EXPERIENCE";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ENGLISH_READ_LEVEL = "ENGLISH_READ_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = "ENGLISH_WRITE_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = "ENGLISH_SPEAK_LEVEL";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = "WHERE_YOU_KNOW_ABOUT_TC";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = "WHY_TAKE_YOU_IN_NETCRACKER";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_MORE_INFORMATION_ADOUT_YOU = "MORE_INFORMATION_ADOUT_YOU";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_INSTITUTE_ID = "INSTITUTE_ID";
    public static final String ATTR_TYPE_CODE_QA_RESUME_DETAIL_RESUME_ID = "RESUME_ID";

    //QA_INTERVIEW_RESULT_DETAIL
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_COME_TO_INTERVIEW = "HR_COME_TO_INTERVIEW";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = "HR_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = "HR_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = "HR_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_1 = "QA_KNOWLEDGE_1";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_2 = "QA_KNOWLEDGE_2";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_3 = "QA_KNOWLEDGE_3";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_4 = "QA_KNOWLEDGE_4";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_5 = "QA_KNOWLEDGE_5";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_QA_KNOWLEDGE_6 = "QA_KNOWLEDGE_6";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_1 = "IT_KNOWLEDGE_1";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_2 = "IT_KNOWLEDGE_2";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_3 = "IT_KNOWLEDGE_3";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_IT_KNOWLEDGE_4 = "IT_KNOWLEDGE_4";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_FINAL_ASSESSMENT = "INTERVIEWER_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_BASIC_INFORMATION = "INTERVIEWER_BASIC_INFORMATION";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = "INTERVIEWER_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = "INTERVIEWER_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEWER_COME_TO_INTERVIEW = "INTERVIEWER_COME_TO_INTERVIEW";
    public static final String ATTR_TYPE_CODE_QA_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = "INTERVIEW_RESULT_ID";

    //POSITION
    public static final String ATTR_TYPE_CODE_POSITION_ID = "ID";
    public static final String ATTR_TYPE_CODE_POSITION_DESCRIPTION = "DESCRIPTION";

    //MAIL_QUEUE
    public static final String ATTR_TYPE_CODE_MAIL_QUEUE_ID = "ID";
    public static final String ATTR_TYPE_CODE_MAIL_QUEUE_ADDED_WHEN = "ADDED_WHEN";
    public static final String ATTR_TYPE_CODE_MAIL_QUEUE_IS_SENT = "IS_SENT";
    public static final String ATTR_TYPE_CODE_MAIL_IS_INCORRECT_MAIL = "IS_INCORRECT_MAIL";
    public static final String ATTR_TYPE_CODE_MAIL_RECIVER_ADDRESS = "RECIVER_ADDRESS";
    public static final String ATTR_TYPE_CODE_MAIL_MESSAGE_SUBJECT = "MESSAGE_SUBJECT";
    public static final String ATTR_TYPE_CODE_MAIL_MESSAGE_BODY = "MESSAGE_BODY";

    //KNOWLEDGE_TYPE
    public static final String ATTR_TYPE_CODE_KNOWLEDGE_TYPE_ID = "ID";
    public static final String ATTR_TYPE_CODE_KNOWLEDGE_TYPE_DESCRIPTION = "DESCRIPTION";

    //INTERVIEW_SLOT
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_ID = "ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_TIME = "TIME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_INTERVIEW_ID = "INTERVIEW_ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_SLOT_USER_ID = "USER_ID";

    //INTERVIEW_RESULT
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_INTERVIEW_SLOT_ID = "INTERVIEW_SLOT_ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_IS_COME = "IS_COME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_HR_USER_ID = "HR_USER_ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_RESULT_INTERVIEWER_USER_ID = "INTERVIEWER_USER_ID";

    //INTERVIEW
    public static final String ATTR_TYPE_CODE_INTERVIEW_ID = "ID";
    public static final String ATTR_TYPE_CODE_INTERVIEW_LOGIN = "LOGIN";
    public static final String ATTR_TYPE_CODE_INTERVIEW_START_TIME = "START_TIME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_END_TIME = "END_TIME";
    public static final String ATTR_TYPE_CODE_INTERVIEW_HR_TIME_FOR_INTERVIEW = "HR_TIME_FOR_INTERVIEW";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_TIME_FOR_INTERVIEW = "INTERVIEW_TIME_FOR_INTERVIEW";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_TOTAL_PLACE_COUNT = "TOTAL_PLACE_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_AVAILABLE_PLACE_COUNT = "AVAILABLE_PLACE_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_INTERVIEW_COUNT = "INTERVIEW_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_HR_COUNT = "HR_COUNT";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_ENABLE = "ENABLE";
    public static final String ATTR_TYPE_CODE_INTERVIEW_INTERVIEW_POSITION_ID = "POSITION_ID";

    //INSTITUTE
    public static final String ATTR_TYPE_CODE_INSTITUTE_ID = "ID";
    public static final String ATTR_TYPE_CODE_INSTITUTE_DESCRIPTION = "DESCRIPTION";

    //DEV_RESUME_DETAIL
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_INSTITUTE_OTHER_NAME = "INSTITUTE_OTHER_NAME";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_COURCE = "COURCE";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_FACULTY = "FACULTY";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_DEPARTMENT = "DEPARTMENT";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_SPECIALITY = "SPECIALITY";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_GRADUATION_YEAR = "GRADUATION_YEAR";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_CONTACTS = "OTHER_CONTACTS";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_TRAINING_CENTER_INTEREST = "TRAINING_CENTER_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WORK_IN_NETCRACKER_INTEREST = "WORK_IN_NETCRACKER_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_JOB_INTEREST = "OTHER_JOB_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_BACK_END_INTEREST = "BACK_END_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_FRONT_END_INTEREST = "FRONT_END_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_DB_INTEREST = "DB_INTEREST";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_WORK_TYPE_SPECIFIC = "OTHER_WORK_TYPE_SPECIFIC";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OPP_LEVEL = "OPP_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_DB_LEVEL = "DB_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WEB_LEVEL = "WEB_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_USER_INTERFACE_LEVEL = "USER_INTERFACE_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_UML_LEVEL = "UML_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_OTHER_SKILL_LEVEL = "OTHER_SKILL_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WORK_EXPERIENCE = "WORK_EXPERIENCE";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ENGLISH_READ_LEVEL = "ENGLISH_READ_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ENGLISH_WRITE_LEVEL = "ENGLISH_WRITE_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_ENGLISH_SPEAK_LEVEL = "ENGLISH_SPEAK_LEVEL";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WHERE_YOU_KNOW_ABOUT_TC = "WHERE_YOU_KNOW_ABOUT_TC";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_WHY_TAKE_YOU_IN_NETCRACKER = "WHY_TAKE_YOU_IN_NETCRACKER";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_MORE_INFORMATION_ABOUT_YOU = "MORE_INFORMATION_ABOUT_YOU";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_INSTITUTE_ID = "INSTITUTE_ID";
    public static final String ATTR_TYPE_CODE_DEV_RESUME_DETAIL_RESUME_ID = "RESUME_ID";

    //DEV_INTERVIEW_RESULT_DETAIL
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_ID = "ID";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_JAVA_SKILL = "JAVA_SKILL";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_SQL_SKILL = "SQL_SKILL";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_OTHER_INFORMATION = "INTERVIEWER_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEWER_WORK_WITH_USER = "INTERVIEWER_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_HR_OTHER_INFORMATION = "HR_OTHER_INFORMATION";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_HR_WORK_WITH_USER = "HR_WORK_WITH_USER";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_DEV_FINAL_ASSESSMENT = "DEV_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_HR_FINAL_ASSESSMENT = "HR_FINAL_ASSESSMENT";
    public static final String ATTR_TYPE_CODE_DEV_INTERVIEW_RESULT_DETAIL_INTERVIEW_RESULT_ID = "INTERVIEW_RESULT_ID";

}
